services:
  - type: web
    name: stats-hockey
    env: python
    buildCommand: ""
    startCommand: "python agent_stats_hockey.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
